#!/bin/bash
echo "`ifconfig eth0 | grep broadcast | awk '{print $2}'` `hostname` `hostname -s`" >> /etc/hosts
setenforce permissive
sed -i.bak "s/SELINUX=enforcing/SELINUX=permissive/g" /etc/selinux/config
sed -i.bak "s/#UseDNS yes/UseDNS no/g" /etc/ssh/sshd_config

cat > /etc/yum.repos.d/virt7-docker-common-release.repo << EOF
[virt7-docker-common-release]
name=virt7-docker-common-release
baseurl=http://cbs.centos.org/repos/virt7-docker-common-release/x86_64/os/
gpgcheck=0
EOF
yum install kubernetes flannel vim -y

cat > /etc/kubernetes/config << EOF
KUBE_LOGTOSTDERR="--logtostderr=true"
KUBE_LOG_LEVEL="--v=0"
KUBE_ALLOW_PRIV="--allow-privileged=false"
KUBE_MASTER="--master=http://$1:8080"
EOF

cat > /etc/kubernetes/kubelet << EOF
KUBELET_ADDRESS="--address=0.0.0.0"
# KUBELET_PORT="--port=10250"
KUBELET_HOSTNAME="--hostname-override=$HOSTNAME"
KUBELET_API_SERVER="--api-servers=http://$1:8080"
KUBELET_POD_INFRA_CONTAINER="--pod-infra-container-image=registry.access.redhat.com/rhel7/pod-infrastructure:latest"
KUBELET_ARGS=""
EOF

cat > /etc/sysconfig/flanneld << EOF
FLANNEL_ETCD="http://$1:2379"
FLANNEL_ETCD_KEY="/atomic.io/network"
#FLANNEL_OPTIONS=""
EOF
systemctl restart kube-proxy kubelet docker flanneld
systemctl enable kube-proxy kubelet docker flanneld
