#!/bin/bash
### links ###
# http://kubernetes.io/v1.0/docs/getting-started-guides/aws/kubectl.html
# http://kubernetes.io/v1.1/docs/getting-started-guides/docker.html

msg_padrao="
\nflag padrao, valores aceitaveis:
\n -e | --etcd
\n -m | --master
\n -p | --proxy
\n -k | --kubectl
\n -a | --all
\n -c | --clear
\n -h --help
"

etcd(){
	### run etcd
	docker run --net=host \
	-d gcr.io/google_containers/etcd:2.0.12 /usr/local/bin/etcd \
	--addr=127.0.0.1:4001 --bind-addr=0.0.0.0:4001 \
	--data-dir=/var/etcd/data
}

master(){
	### run master
	docker run \
	--volume=/:/rootfs:ro \
	--volume=/sys:/sys:ro --volume=/dev:/dev \
	--volume=/var/lib/docker/:/var/lib/docker:ro \
	--volume=/var/lib/kubelet/:/var/lib/kubelet:rw \
	--volume=/var/run:/var/run:rw \
	--net=host --pid=host --privileged=true \
	-d gcr.io/google_containers/hyperkube:v1.0.1 /hyperkube kubelet \
	--containerized --hostname-override="127.0.0.1" \
	--address="0.0.0.0" --api-servers=http://localhost:8080 \
	--config=/etc/kubernetes/manifests
}

proxy(){
	### run proxy
	docker run -d --net=host \
	--privileged gcr.io/google_containers/hyperkube:v1.0.1 /hyperkube proxy \
	--master=http://127.0.0.1:8080 --v=2
}

kubectl(){
	### manager kubectl
	wget https://storage.googleapis.com/kubernetes-release/release/v1.0.1/bin/linux/amd64/kubectl
	chmod +x kubectl ; mv kubectl /usr/local/bin/
}

conteiners_cls(){
	docker ps -a | awk '{print $1}' | grep -v CONTAINER | while read saida
	do
		docker rm -f $saida
	done
}

while test -n "$1"
do
	case $1 in
		-e | --etcd) etcd ;;
		-m | --master) master ;;
		-p | --proxy) proxy ;;
		-k | --kubectl) kubectl ;;
		-c | --clear) conteiners_cls ;;
		-a | --all)
			etcd
			master
			proxy
			kubectl
		;;
		*) echo -e $msg_padrao
	esac
	shift
done
