#!/bin/bash

etcd_bind=`ifconfig eth0 | grep broadcast | awk '{print $2}'`

# Datastore
docker run -ti -d --restart=always --name shipyard-rethinkdb rethinkdb

# Discovery
docker run -ti -d -p 4001:4001 -p 7001:7001 --restart=always \
    --name shipyard-discovery microbox/etcd -name discovery

# Proxy
docker run -ti -d -p 2375:2375 --hostname=$HOSTNAME --restart=always \
    --name shipyard-proxy -v /var/run/docker.sock:/var/run/docker.sock \
    -e PORT=2375 shipyard/docker-proxy:latest

# Swarm Manager
docker run -ti -d --restart=always --name shipyard-swarm-manager \
    swarm:latest manage --host tcp://0.0.0.0:3375 etcd://$etcd_bind:4001

# Swarm Agent
docker run -ti -d --restart=always --name shipyard-swarm-agent \
    swarm:latest join --addr $etcd_bind:2375 etcd://$etcd_bind:4001

# Controller
docker run -ti -d --restart=always --name shipyard-controller \
    --link shipyard-rethinkdb:rethinkdb \
    --link shipyard-swarm-manager:swarm -p 80:8080 \
    shipyard/shipyard:latest server -d tcp://swarm:3375
