#!/bin/bash
fixed_roles(){
        iptables $1 FORWARD -p tcp --dport 53 -j ACCEPT
        iptables $1 FORWARD -p udp --dport 53 -j ACCEPT

        iptables $1 FORWARD -p tcp --sport 53 -j ACCEPT
        iptables $1 FORWARD -p udp --sport 53 -j ACCEPT


        iptables $1 FORWARD -p tcp --dport 587 -j ACCEPT
        iptables $1 FORWARD -p tcp --dport 110 -j ACCEPT

        iptables $1 FORWARD -p tcp --sport 587 -j ACCEPT
        iptables $1 FORWARD -p tcp --sport 110 -j ACCEPT
}

fixed_roles -D
fixed_roles -A
