#!/bin/bash
pref_so(){
	setenforce permissive
	sed -i.bak "s/SELINUX=enforcing/SELINUX=permissive/g" /etc/selinux/config
	sed -i.bak "s/#UseDNS yes/UseDNS no/g" /etc/ssh/sshd_config
	systemctl disable firewalld.service
	systemctl stop firewalld.service
	iptables --flush
}

gen_screenrc(){
cat > $HOME/.screenrc << EOF
msgwait 3
sorendition 05 29
#hardstatus alwayslastline " %c | %d/%m/%Y | %w"
#bind h hardstatus ignore
#bind g hardstatus alwayslastline
hardstatus alwayslastline
hardstatus string "%{= kG} [ %{= W} %-Lw%{=r}%n* %t%{-}%+Lw %= %{G}] [ %{W}@%H %d-%m %c %{G}] "
#hardstatus string "%{= kG} %{= w}%-Lw%{=r}%n%f* %t%{-}%+LW"
# hardstatus string '%{= kG}[ %{G}%H %{g}][%= %{= kw}%?%-Lw%?%{r}(%{W}%n*%f%t%?(%u)%?%{r})%{w}%?%+Lw%?%?%= %{g}][%{B} %m-%d %{W}%c %{g}]'
vbell off #flashs na tela removidos
EOF
}

hostname_manager(){
	dominio=""
	if grep -q \\. /etc/hostname
	then
		dominio=`cat /etc/hostname | cut -d . -f2`
		hostname `cat /etc/hostname`
	elif hostname | grep -q \\.
	then
		dominio=`hostname | cut -d . -f2`
		hostname > /etc/hostname
	else
		echo "nao foi encontrado dominio, entre com o dominio"
                read dominio
                hostname "`hostname`.$dominio"
                echo `hostname` > /etc/hostname
	fi

	echo "`ifconfig eth0 | grep broadcast | awk '{print $2}'` `hostname`" >> /etc/hosts

	if [ -f /etc/cloud/cloud.cfg ]
	then
		cat /etc/cloud/cloud.cfg | grep -v host > /tmp/cloud.cfg
		mv /tmp/cloud.cfg /etc/cloud/
	fi
}
pref_so
hostname_manager
gen_screenrc
