#!/bin/bash
packages(){
        wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | apt-key add -
        echo "deb http://download.virtualbox.org/virtualbox/debian jessie contrib non-free" > /etc/apt/sources.list.d/virtualbox.list
        apt-get update
	apt-get install build-essential dkms unzip wget -y
        apt-get install apache2 php5 php5-common php-soap php5-gd virtualbox-5.0 -y
        wget -q -P /tmp https://sourceforge.net/projects/phpvirtualbox/files/phpvirtualbox-5.0-5.zip
	wget -q -P /tmp http://download.virtualbox.org/virtualbox/5.0.16/Oracle_VM_VirtualBox_Extension_Pack-5.0.16-105871.vbox-extpack
}

config_php(){
cat > /var/www/html/config.php << EOF
<?php
class phpVBoxConfig {

var \$username = '$1';
var \$password = '$2';
var \$location = 'http://127.0.0.1:18083/';
var \$language = 'en';
var \$vrdeports = '9000-9100';

/*
var \$servers = array(
        array(
                'name' => 'London',
                'username' => 'user',
                'password' => 'pass',
                'location' => 'http://192.168.1.1:18083/',
                'authMaster' => true // Use this server for authentication
        ),
        array(
                'name' => 'New York',
                'username' => 'user2',
                'password' => 'pass2',
                'location' => 'http://192.168.1.2:18083/'
        ),
);
*/

#var \$noAuth = true;
#var \$consoleHost = '192.168.1.40';
#var \$noPreview = true;
#var \$previewUpdateInterval = 30;
#var \$previewWidth = 180;

var \$maxProgressList = 5;

#var \$previewAspectRatio = 1.6;
#var \$enableCustomIcons = true;
#var \$phpVboxGroups = true;

var \$deleteOnRemove = true;
var \$browserRestrictFiles = array('.iso','.vdi','.vmdk','.img','.bin','.vhd','.hdd','.ovf','.ova','.xml','.vbox','.cdr','.dmg','.ima','.dsk','.vfd');

#var \$browserRestrictFolders = array('D:\\','C:\\Users\\Ian'); // Or something like array('/home/vbox','/var/ISOs')
#var \$browserLocal = true;
#var \$browserDisable = true;
#var \$noWindowsDriveList = true;
#var \$forceWindowsAllDriveList = true;

var \$hostMemInfoRefreshInterval = 5;

#var \$hostMemInfoShowFreePct = true;
#var \$vmMemoryStartLimitWarn = true;
#var \$vmMemoryOffset = 100;
#var \$enableGuestAdditionsVersionDisplay = true;
#var \$disableTabVMSnapshots = true; // Snapshots tab
#var \$disableTabVMConsole = true; // Console tab

var \$consoleResolutions = array('640x480','800x600','1024x768','1280x720','1440x900');
var \$consoleKeyboardLayout = 'EN';
var \$nicMax = 4;

#var \$enableAdvancedConfig = true;
#var \$startStopConfig = true;
#var \$enforceVMOwnership = true;
#var \$vmQuotaPerUser = 2;
#var \$enableVDE = true; 
#var \$disableSataPortCount = true;
#var \$enableLPTConfig = true;
#var \$enableHDFlushConfig = true;
#var \$eventListenerTimeout = 20;
}
EOF
}

deploy_web(){
	unzip /tmp/phpvirtualbox-5.0-5.zip -d /tmp
	rm -rf /var/www/html/
	mv /tmp/phpvirtualbox-5.0-5 /var/www/html
	useradd -s /bin/bash -g vboxusers -m managervbox
	echo -e "new_password\nnew_password" | (passwd managervbox)
	config_php managervbox new_password
	chown -R managervbox. /var/www/html
	vboxmanage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-5.0.16-105871.vbox-extpack
}


purge_vboxweb(){
	vboxmanage extpack uninstall --force VirtualBox-5.0.16-105871-Linux_amd64

	rm -rf /tmp/phpvirtualbox-5.0-5.zip /var/www/html/ /tmp/phpvirtualbox-5.0-5 \
	/tmp/Oracle_VM_VirtualBox_Extension_Pack-5.0.16-105871.vbox-extpack /etc/apt/sources.list.d/virtualbox.list
		
	apt-get remove build-essential dkms unzip whet -y
        apt-get remove apache2 php5 php5-common php-soap php5-gd virtualbox-5.0 -y

	userdel -r managervbox
}

msg_padrao="
\nflag padrao, valores aceitaveis:
\n -i --install
\n -r --remove
\n -v --version
\n -h --help
prog -i (instala)
prog -r (unistall)
"

while test -n "$1"
do
	case $1 in
		-i | --install)
			packages
			deploy_web
		;;
		-r | --remove) purge_vboxweb ;;
		-v | --version) echo "flag -v ou --version" ;;
		-h | --help) echo "flag -h ou --help" ;;
		*) echo -e $msg_padrao
	esac

	# limpa o valor de $1 ja processado
	# atribui proximo valor a $1
	shift
done
