#!/bin/bash

# funcao de descoberta do sistema operacional
# get_so -s (retorna o sistema operasional)
# get_so -v (versao do sistema)
get_so(){
	while test -n "$1"
	do
	case $1 in
		-s | --operatingsystem)
			cat /etc/os-release | grep PRETTY_NAME= | cut -d \" -f 2 | awk '{print $1}'
		;;
		-v | --version)
			cat /etc/os-release | grep VERSION_ID= | cut -d \" -f2
		;;
		*) echo "opcao invalida"
	esac
	shift
	done
}

#### funcoes de gerencia ####
# funcao para gerar config.php
# uso config_php user senha
config_php(){
cat > $root_web/config.php << EOF
<?php
# arquivo gerado no deploy, arquivo completo em $root_web/config.php-example
class phpVBoxConfig {

var \$username = '$1';
var \$password = '$2';
var \$location = 'http://127.0.0.1:18083/';
var \$language = 'en';
var \$vrdeports = '9000-9100';

var \$maxProgressList = 5;

var \$deleteOnRemove = true;
var \$browserRestrictFiles = array('.iso','.vdi','.vmdk','.img','.bin','.vhd','.hdd','.ovf','.ova','.xml','.vbox','.cdr','.dmg','.ima','.dsk','.vfd');

var \$hostMemInfoRefreshInterval = 5;

var \$consoleResolutions = array('640x480','800x600','1024x768','1280x720','1440x900');
var \$consoleKeyboardLayout = 'EN';
var \$nicMax = 4;

}
EOF
}

# funcao para instalar pacotes em sos debian e ubuntu
# setar variavel pkg_apt antes
ubt_debinstall(){
	wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | apt-key add -
	apt-get update
	apt-get install $pkg_apt -y
	services_restarted="vboxweb-service vboxdrv apache2"
}

# funcao para configurar anbiente vbox com vboxweb
# setar variaveis services_restarted e root_web antes
# essa funcao depende da funcao config_php
deploy_web(){
	unzip /tmp/phpvirtualbox-5.0-5.zip -d /tmp
	rm -rf $root_web
	mv /tmp/phpvirtualbox-5.0-5 $root_web
	useradd -s /bin/bash -g vboxusers -m managervbox
	echo -e "new_password\nnew_password" | (passwd managervbox)
	config_php managervbox new_password
	echo "VBOXWEB_USER=managervbox" > /etc/default/virtualbox
	chown -R managervbox. /var/www/html
	vboxmanage extpack install /tmp/Oracle_VM_VirtualBox_Extension_Pack-${vbox_version}.vbox-extpack
	systemctl restart $services_restarted
}

packages(){
root_web="/var/www/html"
	case `get_so -s` in
		Debian)
			echo "deb http://download.virtualbox.org/virtualbox/debian jessie contrib non-free" \
			> /etc/apt/sources.list.d/virtualbox.list
		ubt_debinstall
		;;
		Ubuntu)
 			echo "deb http://download.virtualbox.org/virtualbox/debian wily contrib" \
			> /etc/apt/sources.list.d/virtualbox.list
			ubt_debinstall
		;;
		CentOS)
 			setenforce permissive
			sed -i.bak "s/SELINUX=enforcing/SELINUX=permissive/g" /etc/selinux/config
			sed -i.bak "s/#UseDNS yes/UseDNS no/g" /etc/ssh/sshd_config
			systemctl disable firewalld.service
			systemctl stop firewalld.service
			iptables --flush
			yum install -y epel-release
			wget -P /etc/yum.repos.d/ http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo
			echo "yum install -y $pkg_yum"
			yum install -y $pkg_yum
			services_restarted="vboxweb-service vboxdrv httpd"
		;;
	esac

	vbox_version="$(vboxmanage --version | tail -n1 | cut -d r -f 1)"
	wget -q -P /tmp https://sourceforge.net/projects/phpvirtualbox/files/phpvirtualbox-5.0-5.zip
	wget -q -P /tmp http://download.virtualbox.org/virtualbox/$vbox_version/Oracle_VM_VirtualBox_Extension_Pack-${vbox_version}.vbox-extpack
}


purge_vboxweb(){
	vbox_version="$(vboxmanage --version | tail -n1 | cut -d r -f 1)"
	vboxmanage extpack uninstall --force VirtualBox-${vbox_version}-Linux_amd64

	rm -rf /tmp/phpvirtualbox-5.0-5.zip /var/www/html/ /tmp/phpvirtualbox-5.0-5 \
	/tmp/Oracle_VM_VirtualBox_Extension_Pack-${vbox_version}.vbox-extpack /etc/apt/sources.list.d/virtualbox.list
		
	case `get_so -s` in
		Debian)
			echo "pacotes removidos: $pkg_apt"
			echo "para cancelar CTRL + C"
			echo "continuar ENTER"
			read
			apt-get remove $pkg_apt -y
			apt-get autoremove -y
		;;
		Ubuntu)
			echo "pacotes removidos: $pkg_apt"
			echo "para cancelar CTRL + C"
			echo "continuar ENTER"
			read
			apt-get remove $pkg_apt -y
			apt-get autoremove -y
		;;
		CentOS)
			pkg_yum=$(echo $pkg_yum | sed "s/binutils //g")
			echo "pacotes removidos: $pkg_yum"
			echo "para cancelar CTRL + C"
			echo "continuar ENTER"
			read
			yum erase $pkg_yum -y
			rm -rf /etc/yum.repos.d/virtualbox.repo*
		;;
	esac

	userdel -r managervbox
}

msg_padrao="
\nflag padrao, valores aceitaveis:
\n -i --install
\n -r --remove
prog -i (instala)
prog -r (unistall)
"
pkg_yum="binutils gcc make patch libgomp glibc-headers glibc-devel kernel-headers
kernel-devel dkms unzip wget httpd php php-soap php-gd VirtualBox-5.0"

pkg_apt="build-essential dkms unzip wget apache2 php5 php5-common php-soap
php5-gd virtualbox-5.0"

while test -n "$1"
do
	case $1 in
		-i | --install)
			packages
			deploy_web
		;;
		-r | --remove) purge_vboxweb ;;
		-v | --version) echo "flag -v ou --version" ;;
		*) echo -e $msg_padrao
	esac

	shift
done
