#!/bin/bash
sudo apt install nodejs npm-y
sudo npm install nativefier -g
mkdir ~/.webapp/
cd ~/.webapp/
nativefier --name "OneDrive" \
	"https://alpinerescueteam-my.sharepoint.com/personal/narigacdo_mail_anandaigueschools_org/_layouts/15/onedrive.aspx"

cat > ~/.local/share/applications/onedrive.desktop < EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=One Drive
Comment=Web Application for One Drive
Path=~/.webapp/OneDrive-linux-x64/
Exec=~/.webapp/OneDrive-linux-x64/OneDrive
Icon=~/.webapp/OneDrive-linux-x64/resources/app/icon.png
Terminal=false
Categories=Storage;Cloud;
EOF
