#!/bin/bash

hammer -u admin -p 'nada@nada' location create --name jab
export loc_id=$(hammer -u admin -p 'nada@nada' location list | grep jab | awk '{print $1}')

hammer -u admin -p 'nada@nada' organization create --name 'home' --label 'home' --description 'My Home'
export org_id=$(hammer -u admin -p 'nada@nada'  organization list | grep home | awk '{print $1}')

hammer -u admin -p 'nada@nada' user create --admin yes --default-location-id $loc_id \
--default-organization-id $org_id --login nariga --mail adriano@nada \
--firstname Adriano --lastname Lopes --password 'nada@nada' --organizations home \
--locations jab --auth-source-id 1
