#!/bin/bash
# Configura smart-proxy como dhcp e tftp
# Deve-se alterar foreman-proxy-dhcp-interface, ips e dominios
prepare_so(){
	echo "deb http://deb.theforeman.org/ jessie 1.11" > /etc/apt/sources.list.d/foreman.list
	echo "deb http://deb.theforeman.org/ plugins 1.11" >> /etc/apt/sources.list.d/foreman.list
	apt-get -y install ca-certificates
	wget -q https://deb.theforeman.org/pubkey.gpg -O- | apt-key add -
	apt-get update && apt-get -y install foreman-installer

	grep -q ^net.ipv4.ip_forward=1 /etc/sysctl.conf || echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
	iptables -nL -t nat | grep ^"MASQUERADE  all  --  0.0.0.0/0            0.0.0.0/0" || \
		iptables -t nat -A POSTROUTING -j MASQUERADE
}

installer_conf(){
	foreman-installer \
	  --no-enable-foreman \
	  --no-enable-foreman-cli \
	  --no-enable-foreman-plugin-bootdisk \
	  --no-enable-foreman-plugin-setup \
	  --no-enable-puppet \
	  --enable-foreman-proxy \
	  --foreman-proxy-puppetca=false \
	  --foreman-proxy-puppetrun=false \
	  --foreman-proxy-tftp=true \
	  --foreman-proxy-tftp-servername=192.168.212.1 \
	  --foreman-proxy-dhcp=true \
	  --foreman-proxy-dhcp-interface=eth1 \
	  --foreman-proxy-dhcp-gateway=192.168.212.1 \
	  --foreman-proxy-dhcp-range="192.168.212.2 192.168.212.30" \
	  --foreman-proxy-dhcp-nameservers="192.168.212.1,8.8.8.8" \
	  --foreman-proxy-foreman-base-url=https://foreman.home.jab \
	  --foreman-proxy-dns=true \
	  --foreman-proxy-dns-interface=eth1 \
	  --foreman-proxy-dns-zone=vostro.internal \
	  --foreman-proxy-dns-reverse=212.168.192.in-addr.arpa \
	  --foreman-proxy-dns-forwarders=8.8.8.8 \
	  --foreman-proxy-dns-forwarders=8.8.4.4 \
	  --foreman-proxy-trusted-hosts=foreman.home.jab \
	  --foreman-proxy-oauth-consumer-key=fRNBNoYL9JNwmTh2zsbuCXDpCFBeFanC \
	  --foreman-proxy-oauth-consumer-secret=soG887jiZW2T2eZEcqhP9U3tULkfRrQT
}

add_zone(){
cat >> /etc/bind/zones.conf << EOF

zone "conteiner" {
    type master;
    file "/var/cache/bind/zones/db.conteiner";
    update-policy {
            grant rndc-key zonesub ANY;
    };
};
EOF

cat > /var/cache/bind/zones/db.conteiner << EOF
$TTL 10800
@ IN SOA gateway.local.uol. root.local.uol. (
        1       ;Serial
        86400   ;Refresh
        3600    ;Retry
        604800  ;Expire
        3600    ;Negative caching TTL
)

@ IN NS gateway.local.uol.
foreman.conteiner. IN A 192.168.100.241
EOF
}

prepare_so
installer_conf
