#!/bin/bash
# Configura smart-proxy como dhcp e tftp
# Deve-se alterar foreman-proxy-dhcp-interface, ips e dominios
prepare_so(){
	echo "deb http://deb.theforeman.org/ jessie 1.11" > /etc/apt/sources.list.d/foreman.list
	echo "deb http://deb.theforeman.org/ plugins 1.11" >> /etc/apt/sources.list.d/foreman.list
	apt-get -y install ca-certificates
	wget -q https://deb.theforeman.org/pubkey.gpg -O- | apt-key add -
	apt-get update && apt-get -y install foreman-installer
}

installer_conf(){
	foreman-installer \
	  --no-enable-foreman \
	  --no-enable-foreman-cli \
	  --no-enable-foreman-plugin-bootdisk \
	  --no-enable-foreman-plugin-setup \
	  --no-enable-puppet \
	  --enable-foreman-proxy \
	  --foreman-proxy-puppetca=false \
	  --foreman-proxy-puppetrun=false \
	  --foreman-proxy-tftp=true \
	  --foreman-proxy-tftp-servername=192.168.200.254 \
	  --foreman-proxy-dhcp=true \
	  --foreman-proxy-dhcp-interface=eth1 \
	  --foreman-proxy-dhcp-gateway=192.168.200.254 \
	  --foreman-proxy-dhcp-range="192.168.200.242 192.168.200.253" \
	  --foreman-proxy-dhcp-nameservers="192.168.200.254,8.8.8.8" \
	  --foreman-proxy-foreman-base-url=https://foreman.conteiner \
	  --foreman-proxy-dns=true \
	  --foreman-proxy-dns-interface=eth1 \
	  --foreman-proxy-dns-zone=local.uol \
	  --foreman-proxy-dns-reverse=200.168.192.in-addr.arpa \
	  --foreman-proxy-dns-forwarders=8.8.8.8 \
	  --foreman-proxy-dns-forwarders=8.8.4.4 \
	  --foreman-proxy-trusted-hosts=foreman.conteiner \
	  --foreman-proxy-oauth-consumer-key=XhXvzgvUTZ9RrKqoBKSw67sGamTHpyCS \
	  --foreman-proxy-oauth-consumer-secret=uzyN2LpbxE7nXVugNA5iuNCPhkTY4bb5
}

prepare_so
installer_conf
