#cloud-config
# coreos-install -d /dev/sda -C stable -c install.yml
hostname: "template.coreos"

users:
  - name: "nariga"
    passwd: "$1$a.ozvOT7$2EpeS59FrUA00d0BBTr091"
    groups:
      - "sudo"
      - "docker"
    ssh-authorized-keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEg86Ari5/rf7HCrY2UZ0mdWnRElvXyaoYbIDsFR1f4RqQPjyJ9WIslabyWt+sEItz8gPcz6Ugogb0u73ByabnfdACspuctivzWPMdDO4PAD0GLJUr4NRmE3ygGwa7k/LnkTmnU9bwe5qmLyuX8YS4A0derUuxxcQT34QZFR1YXd8J1mmo6bpNRvQ7EmuHIqh3GzA1CsJ+giO+gRhHPFV1G05qxjbh30YwnbLpcJB+z0gPucjzVbiW+j8/G+k5y5zaWu/JMbuC88vJoyf4ZH/eNM6xIqVsAMWLO7MkQbdA2bgcRyLniI5FaPU8HeDvVZ/UsTPeAOGWj1OAvdlqOPa5 foreman-proxy@tftp.local"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfUkC+X0K85f5XifA8COA9wnoSOL/VJZrz6sK72REjlnYgkGF7/ggee7AryGFcHdewlDTUxrmLJ/0EkYjBtP6xUhySRr+Z2TDsgyUFcqmKhsK91gVoyOfcKw/TPKRV1z4Sp9Xe3ZU6fLl7IG1UyDxYXf/RCyMHWx44Le2YsNxbQPqwAW/5ihskrMkCt3iZMMy3SFDYnq02ua9t/5SYfV0ulLXbWjI3Ry9oJk7jwnbd65YfH/OXHDiBVGF8e6e043vx0+jy+k2DK+DGXeFtYlLBzfH5ey3IbCHumujSycIBRvw9SyhInwthcVpCBfFp6eTd0AgzgrRt41RzBZ9RjD0p nariga@active-book"
