#!/bin/bash
sep=:
mascara=§
temp=temp.$$

[ "$banco" ] || {
	echo "Base de dados nao informada, use a variavel banco"
	return 1
}

[ -r "$banco" -a -w "$banco" ] || {
	echo "Base travada em: $banco, confira as permissoes"
	return 1
}

mascara(){ tr $sep $mascara ; }
desmascara(){ tr $mascara $sep ; }

tem_chave(){
	grep -i -q "^$1$sep" "$banco"
}

campos(){
	head -n 1 "$banco" | tr $sep \\n
}

apaga_registro(){
	tem_chave "$1" || return
	grep -i -v "^$1$sep" "$banco" > "$temp"
	mv "$temp" "$banco"
	echo "O registro '$1' foi apagado"
}

insere_registro(){
	local chave$(echo "$1" | cut -d $sep -f1)
	if tem_chave $chave
	then
		echo "A chave '$chave' ja esta cadastrada no banco"
		return 1
	else
		echo $* >> "$banco"
		echo "Registro '$chave' cadastrada com sucesso"
	fi
	return 0
}

mostra_registro(){
	local dados=$(grep -i "^$1$sep" "$banco")
	local i=0
	[ "$dados" ] || return
	campos | while read campo
	do
		i=$((i+1))
		echo -n "$campo: "
		echo "$dados" | cut -d $sep -f $i | desmascara
	done
}

pega_campo(){
	local chave=${2:-.*}
	grep -i "^$chave$sep" "$banco" | cut -d $sep -f $1 | desmascara
}
