#!/bin/bash
CONFIG="mensagem.conf"

USAR_CORES=0
COR_LETRA=
COR_FUNDO=
MENSAGEM="Mensagem do script"

eval $(./generic-parser $CONFIG)

[ "$(echo $Conf_USARCORES | tr A-Z a-z)" ] && USAR_CORES=1
COR_LETRA=$(echo $Conf_CORLETRA | tr -d -c 0-9)
COR_FUNDO=$(echo $Conf_CORFUNDO | tr -d -c 0-9)
[ "$Conf_MENSAGEM" ] && MENSAGEM=$Conf_MENSAGEM

### exibe mensagem
# variavel USAR_COR for ligada deve usar cores
if [ $USAR_CORES -eq 1 ]
then
	echo -e "\033[$COR_FUNDO;${COR_LETRA}m$MENSAGEM\033[m"
else
	echo "$MENSAGEM"
fi
