#!/bin/bash
subscription-manager register --username=rhel_nariga --password=peao123$ --force
subscription-manager subscribe --auto
subscription-manager list --consumed
subscription-manager repos --enable=rhel-7-server-rpms
subscription-manager repos --enable=rhel-7-server-rh-common-rpms
subscription-manager repos --enable=rhel-7-server-openstack-7.0-rpms

internal_ip="$(ifconfig enp6s0 | grep broadcast | awk '{print $2}')"
mascara_ip="$(ifconfig enp6s0 | grep broadcast | awk '{print $4}')"
gateway_ip="$(route -n | grep ^0.0.0.0 | awk '{print $2}')"
iface="$(route -n | grep ^0.0.0.0 | awk '{print $8}')"

ifaces(){
br_ex="/etc/sysconfig/network-scripts/ifcfg-br-ex"
ex_if="/etc/sysconfig/network-scripts/ifcfg-$iface"
cat > $br_ex << EOF
DEVICE=br-ex
DEVICETYPE=ovs
TYPE=OVSBridge
BOOTPROTO=static
IPADDR=$internal_ip
NETMASK=$mascara_ip
GATEWAY=$gateway_ip
DNS1=8.8.8.8
ONBOOT=yes
EOF

cat > $ex_if << EOF
DEVICE=eth0
TYPE=OVSPort
DEVICETYPE=ovs
OVS_BRIDGE=br-ex
ONBOOT=yes
EOF
}

provision(){
	systemctl disable NetworkManager
	systemctl enable network
	systemctl disable firewalld
	systemctl stop firewalld
	sed -i.bak "s/SELINUX=enforcing/SELINUX=permissive/g" /etc/selinux/config
	setenforce permissive
	sed -i.bak "s/#UseDNS yes/UseDNS no/g" /etc/ssh/sshd_config
}

rdo_install(){
	packstack --allinone --provision-demo=n \
	--os-neutron-ovs-bridge-mappings=extnet:br-ex \
	--os-neutron-ovs-bridge-interfaces=br-ex:enp6s0 \
	--os-neutron-ml2-type-drivers=vxlan,flat
}
