#!/bin/bash
EASY_RSA_PATH='/etc/openvpn/easy-rsa/'
CERTS_OPENVPN_PATH='/etc/openvpn/certs_server/'

cd $EASY_RSA_PATH
source vars
export hostname=$2
[ ! -d keys ] && mkdir -p keys

gen_certificadora(){
	./clean-all
	./build-ca
	./build-dh
	cp keys/ca.crt $CERTS_OPENVPN_PATH
	cp keys/dh2048.pem $CERTS_OPENVPN_PATH
}

server_cert(){
	echo "$EASY_RSA_PATH/build-key-server $hostname"
	./build-key-server $hostname
	cp keys/"$hostname".crt $CERTS_OPENVPN_PATH
	cp keys/"$hostname".key $CERTS_OPENVPN_PATH
}

client_cert(){
	./build-key $hostname
	cp keys/"$hostname".crt $CERTS_OPENVPN_PATH
	cp keys/"$hostname".key $CERTS_OPENVPN_PATH
	
}

mensagem(){
	echo -e "\n        gerencia de certificados openvpn"
	echo "-s hostname.domain cria o certificado do servidor"
	echo "-c hostneme.domain cria o certificado do cliente"
	echo "-b cria unidade certificadora"
	echo -e "\n             ..... Exemplo ....."
	echo -e "        $0 -c cliente1.domain\n"
}

case $1 in
	'-s') server_cert ;;
	'-c') client_cert ;;
	'-b') gen_certificadora ;;
	*) mensagem ;;
esac
