#!/bin/bash
ips_liberados='ips_liberados'
sysctl net.ipv4.ip_forward=1

enable_forward(){
	iptables -t nat $1 POSTROUTING -j MASQUERADE
}

enable_clear_ips(){
	iptables -P FORWARD DROP
	for i in $(cat $ips_liberados | xargs)
	do
		iptables $1 FORWARD -d $i -j ACCEPT
		iptables $1 FORWARD -s $i -j ACCEPT
	done
}

clear_roles(){
	systemctl stop firewalld
	enable_forward -D
	enable_clear_ips -D
}

clear_roles
enable_forward -A
enable_clear_ips -A
