#!/bin/bash
yum -y install openstack-nova

export OS_TOKEN=admintoken
export OS_URL=http://localhost:35357/v2.0/

mysql -e "create database nova;"
mysql -e "grant all privileges on nova.* to nova@'localhost' identified by 'password';"
mysql -e "grant all privileges on nova.* to nova@'%' identified by 'password';"
mysql -e "flush privileges;"

openstack user create --project service --password servicepassword nova
openstack role add --project service --user nova admin
openstack service create --name nova --description "OpenStack Compute service" compute
export controller="`ip -o -4 a s $(route -n | grep ^0.0.0.0 | awk '{print $8}') | awk '{print $4}' | cut -d / -f 1`"
openstack endpoint create \
--publicurl http://$controller:8774/v2/%\(tenant_id\)s \
--internalurl http://$controller:8774/v2/%\(tenant_id\)s \
--adminurl http://$controller:8774/v2/%\(tenant_id\)s \
--region RegionOne \
compute

sed -i 's/#connection=mysql:\/\/nova:nova@localhost\/nova/connection=mysql:\/\/nova:password@localhost\/nova/g' \
	/etc/nova/nova.conf

chmod 640 /etc/nova/nova.conf
chgrp nova /etc/nova/nova.conf

cat > /etc/sysconfig/network-scripts/ifcfg-dummy0 <<EOF
DEVICE=dummy0
BOOTPROTO=none
ONBOOT=yes
TYPE=Ethernet
NM_CONTROLLED=no
EOF

echo "alias dummy0 dummy" > /etc/modprobe.d/dummy.conf
ifup dummy0
nova-manage db sync
chown -R nova. /var/log/nova
for service in api objectstore conductor scheduler cert consoleauth compute network
do
	systemctl start openstack-nova-$service
	systemctl enable openstack-nova-$service
done
