#!/bin/bash
echo -e "LANG=en_US.utf-8\nLC_ALL=en_US.utf-8\n" > /etc/environment

lsmod | grep -q kvm && lsmod | grep -q kvm || {
	echo "Virtualization guest not enable"
	exit 1
}

grep -q 'ipv6.disable=1' /etc/default/grub && {
	echo "Remove disable ipv6 grub"
	exit 1

}

systemctl disable firewalld
systemctl stop firewalld
systemctl disable NetworkManager
systemctl stop NetworkManager
systemctl enable network
systemctl start network
yum install -y centos-release-openstack-rocky
yum update -y
yum install -y openstack-packstack
packstack --answer-file=packstack-answers.txt

# in /etc/magnum/magnum.conf VV
# [keystone_authtoken]
# www_authenticate_uri=http://10.144.134.12:5000/v3
