heat_template_version: 2013-05-23

parameters:
  image:
    type: string
    description: Image used for servers
    default: CentOS-7 64Bits
  chave:
    type: string
    description: Name of SSH key to connect to the servers
    default: arodrigues
  flavor:
    type: string
    description: flavor used by the servers
    default: small.2GB
    constraints:
      - allowed_values: [ small.1GB, small.2GB, medium.2GB, medium.4GB ]
  num_instances:
    type: number
    description: Number of instances to create
    default: 2
  network:
    type: string
    description: id da rede
    default: 46d9b2da-ee3a-456c-b093-3b413dd98d2f

resources:
  server_config:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_instances }
      resource_def:
        type: OS::Nova::Server
        properties:
          image: { get_param: image }
          flavor: { get_param: flavor}
          key_name: { get_param: chave }
          user_data: |
            #!/bin/bash
            echo "`ifconfig eth0 | grep broadcast | awk '{print $2}'` `hostname`.novalocal" >> /etc/hosts
            setenforce permissive
            sed -i.bak "s/SELINUX=enforcing/SELINUX=permissive/g" /etc/selinux/config
            sed -i.bak "s/#UseDNS yes/UseDNS no/g" /etc/ssh/sshd_config
            systemctl restart sshd
            cat /etc/cloud/cloud.cfg | grep -v host > /tmp/cloud.cfg ; mv /tmp/cloud.cfg /etc/cloud/
            yum -y install httpd
            echo "<h1>`hostname`</h1>" > /usr/share/httpd/noindex/index.html
            systemctl start httpd
            systemctl enable httpd

          user_data_format: RAW
