heat_template_version: 2013-05-23

description: Template simples para deploy de uma instancia

parameters:
  hostname:
    type: string
    description: hostname do servidor foreman
    default: juju.cloud-uol
  chave:
    type: string
    description: nome da chave publica ssh
    default: key
  flavor:
    type: string
    description: escolha de flavor
    constraints:
      - allowed_values: [ small.2GB, medium.4GB, large.16GB, small.4GB, large.8GB micro.1GB, micro.2GB, medium.8GB ]
    default: medium.8GB
  imagem:
    type: string
    description: id ou nome da imagem centos 7
    default: Ubuntu-16.04 64Bits
  network:
    type: string
    description: id da rede
    default: 1ea707c7-ae0a-4c28-b799-72e601f81ee6

resources:
  my_000:
    type: OS::Nova::Server
    properties:
      name: { get_param: hostname }
      key_name: { get_param: chave }
      flavor: { get_param: flavor }
      image: { get_param: imagem }
      networks:
        - port: { get_resource: server_port }
      user_data: |
        #!/bin/bash
        dominio="cloud-uol"
        hostname "`hostname`.$dominio"
        echo `hostname` > /etc/hostname
        echo "`ip a s ens3 | grep inet | grep -v inet6 | cut -d / -f 1 | awk '{print $2}'` `hostname`" >> /etc/hosts
        cat /etc/cloud/cloud.cfg | grep -v host > /tmp/cloud.cfg ; mv /tmp/cloud.cfg /etc/cloud/

        sed -i.bak "s/#UseDNS yes/UseDNS no/g" /etc/ssh/sshd_config
        echo -e "\nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfUkC+X0K85f5XifA8COA9wnoSOL/VJZrz6sK72REjlnYgkGF7/ggee7AryGFcHdewlDTUxrmLJ/0EkYjBtP6xUhySRr+Z2TDsgyUFcqmKhsK91gVoyOfcKw/TPKRV1z4Sp9Xe3ZU6fLl7IG1UyDxYXf/RCyMHWx44Le2YsNxbQPqwAW/5ihskrMkCt3iZMMy3SFDYnq02ua9t/5SYfV0ulLXbWjI3Ry9oJk7jwnbd65YfH/OXHDiBVGF8e6e043vx0+jy+k2DK+DGXeFtYlLBzfH5ey3IbCHumujSycIBRvw9SyhInwthcVpCBfFp6eTd0AgzgrRt41RzBZ9RjD0p nariga@active-book
        \nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdQMpmcqaT02NSs4BpFkiSW+COvSzDPOTaeUL5rZtysGL2X7lLxqPPI1EUhXHvlkM+VZeFNr036wecAGH2hEE6A1L1y/gFsCOgjmshXPZ7+PixkzR4996o9qSks0agNNGUduzsMqEspSffgJM37Ylrh2sXVIzcqq8g0cU/Xe231TgtNWawikR+DyLwuow5FOlrikFt+qnMnhFMgmg6HFom1TtFZX1lLLa8sn+5nYlQrn
        tcOYK2GqbPUtlqNYfzLtEvv39zQWrq/LJIjp1z43O0Z3/RZFQsMOVMGux1+L2TkxCc5elSfJPXWke9p/j02FVpT/Nrv9x97Uq+J68OQqtP nariga@vostro.home.jab" \
        >> /home/administrator/.ssh/authorized_keys
        systemctl restart sshd
        
        add-apt-repository ppa:juju/devel -y
        apt update
        apt install juju zfsutils-linux lxd -y
        newgrp -
        mkdir /var/lib/zfs
        truncate -s 32G /var/lib/zfs/lxd.img
        zpool create lxd /var/lib/zfs/lxd.img

        lxd init --auto --storage-backend zfs --storage-pool lxd
        #dpkg-reconfigure -u -p medium lxd
        #juju bootstrap lxd-test lxd
        #juju switch
        #juju deploy mediawiki-single

      user_data_format: RAW

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network }
      security_groups:
        - SSH-PING
        - WEB

  float_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: public301
  associate_float_ip:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: float_ip }
      server_id: { get_resource: my_000 }

# chamada na api:
# heat stack-create foreman -f HEAT/MY_HEATS/foreman.yaml --parameters 'chave=vostro;hostname=frm01;flavor=small.1GB;admin_password=nada'
