heat_template_version: 2013-05-23

description: Template simples para deploy de uma instancia

parameters:
  hostname:
    type: string
    description: hostname do servidor foreman
    default: katello-3.internal
  chave:
    type: string
    description: nome da chave publica ssh
    default: uol-diveo
  flavor:
    type: string
    description: escolha de flavor
    constraints:
      - allowed_values: [ small.1GB, small.2GB, medium.2GB, medium.4GB, large.4GB ]
    default: large.4GB
  imagem:
    type: string
    description: id ou nome da imagem centos 7
    default: CentOS-7.0-64 bits
  network:
    type: string
    description: id da rede
    default: bb929494-a275-4e81-a689-835dabd37ed1

resources:
  my_000:
    type: OS::Nova::Server
    properties:
      name: { get_param: hostname }
      key_name: { get_param: chave }
      flavor: { get_param: flavor }
      image: { get_param: imagem }
      networks:
        - port: { get_resource: server_port }
      user_data: |
        #!/bin/bash
        dominio="internal"
        hostname "`hostname`.$dominio"
        echo `hostname` > /etc/hostname
        echo "`ifconfig eth0 | grep broadcast | awk '{print $2}'` `hostname`" >> /etc/hosts
        cat /etc/cloud/cloud.cfg | grep -v host > /tmp/cloud.cfg ; mv /tmp/cloud.cfg /etc/cloud/

        setenforce permissive
        sed -i.bak "s/SELINUX=enforcing/SELINUX=permissive/g" /etc/selinux/config
        sed -i.bak "s/#UseDNS yes/UseDNS no/g" /etc/ssh/sshd_config
        echo -e "\nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfUkC+X0K85f5XifA8COA9wnoSOL/VJZrz6sK72REjlnYgkGF7/ggee7AryGFcHdewlDTUxrmLJ/0EkYjBtP6xUhySRr+Z2TDsgyUFcqmKhsK91gVoyOfcKw/TPKRV1z4Sp9Xe3ZU6fLl7IG1UyDxYXf/RCyMHWx44Le2YsNxbQPqwAW/5ihskrMkCt3iZMMy3SFDYnq02ua9t/5SYfV0ulLXbWjI3Ry9oJk7jwnbd65YfH/OXHDiBVGF8e6e043vx0+jy+k2DK+DGXeFtYlLBzfH5ey3IbCHumujSycIBRvw9SyhInwthcVpCBfFp6eTd0AgzgrRt41RzBZ9RjD0p nariga@active-book
        \nssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDdQMpmcqaT02NSs4BpFkiSW+COvSzDPOTaeUL5rZtysGL2X7lLxqPPI1EUhXHvlkM+VZeFNr036wecAGH2hEE6A1L1y/gFsCOgjmshXPZ7+PixkzR4996o9qSks0agNNGUduzsMqEspSffgJM37Ylrh2sXVIzcqq8g0cU/Xe231TgtNWawikR+DyLwuow5FOlrikFt+qnMnhFMgmg6HFom1TtFZX1lLLa8sn+5nYlQrn
        tcOYK2GqbPUtlqNYfzLtEvv39zQWrq/LJIjp1z43O0Z3/RZFQsMOVMGux1+L2TkxCc5elSfJPXWke9p/j02FVpT/Nrv9x97Uq+J68OQqtP nariga@vostro.home.jab" \
        >> /home/administrator/.ssh/authorized_keys
        systemctl restart sshd

        yum -y localinstall http://fedorapeople.org/groups/katello/releases/yum/3.0/katello/RHEL/7Server/x86_64/katello-repos-latest.rpm
        yum -y localinstall http://yum.theforeman.org/nightly/el7/x86_64/foreman-release.rpm
        yum -y localinstall http://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
        yum -y localinstall http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        yum -y install foreman-release-scl
        yum -y install katello

        foreman-installer --foreman-admin-password nada@nada --scenario katello
        sleep 4 ; puppet agent -t

      user_data_format: RAW

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network }
      security_groups:
        - SSH-PING
        - KATELLO

  float_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: publica
  associate_float_ip:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: float_ip }
      server_id: { get_resource: my_000 }

# chamada na api:
# heat stack-create foreman -f HEAT/MY_HEATS/foreman.yaml --parameters 'chave=vostro;hostname=frm01;flavor=small.1GB;admin_password=nada'
