#!/bin/bash
get_so(){
        while test -n "$1"
        do
        case $1 in
                -s | --operatingsystem)
                        grep PRETTY_NAME= /etc/os-release | cut -d \" -f 2 | awk '{print $1}'
                ;;
                -v | --version)
                        grep VERSION_ID= /etc/os-release | cut -d \" -f2
                ;;
                *) echo "opcao invalida"
        esac
        shift
        done
}

pip_extra_pkgs(){
	pip install sklearn joblib pyparsing \
		wrapt debtcollector pytz debtcollector \
		monotonic netaddr shade functools32 --upgrade
}

install_pip(){
	virtualenv /root/.ansible
	source /root/.ansible/bin/activate
	pip install paramiko --upgrade
	pip install paramiko requests --upgrade
	pip install PyYAML Jinja2 httplib2 six \
		markupsafe ecdsa shade apache-libcloud \
		boto PyOpenSSL --upgrade
	pip install ansible --upgrade
}

debian(){
	apt update
	apt install python-dev build-essential python-virtualenv python-pip libssl-dev -y
	pip install --upgrade pip
	install_pip
}

centos(){
	yum install epel-release -y
	yum install \
		python-virtualenv python-pip \
		python-devel gcc gcc-c++ make \
		cmake python-simplejson openssl-devel \
		libffi libffi-devel pyOpenSSL pycryptopp \
		libselinux-python python2 python-simplejson -y
	pip install --upgrade pip
	install_pip
}

case `get_so -s` in
        Ubuntu|elementary|Debian) debian ;;
        CentOS) centos ;;
        Red) if_rhel ;;
esac	\
