#!/bin/bash
get_so(){
        while test -n "$1"
        do
        case $1 in
                -s | --operatingsystem)
                        grep PRETTY_NAME= /etc/os-release | cut -d \" -f 2 | awk '{print $1}'
                ;;
                -v | --version)
                        grep VERSION_ID= /etc/os-release | cut -d \" -f2
                ;;
                *) echo "opcao invalida"
        esac
        shift
        done
}

install_pip(){

	if [ `get_so -v` = "18.04" ]
	then
		python3.6 -m venv /root/.ansible
	else
		virtualenv /root/.ansible
	fi

	source /root/.ansible/bin/activate

	pip install --upgrade pip
	pip install --upgrade setuptools
	pip install --upgrade paramiko requests
	pip install --upgrade PyYAML Jinja2 httplib2
	pip install --upgrade six markupsafe ecdsa
        pip install --upgrade shade apache-libcloud
	pip install --upgrade boto PyOpenSSL python-ldap
	pip install --upgrade sklearn joblib pyparsing
	pip install --upgrade wrapt debtcollector pytz
	pip install --upgrade debtcollector monotonic
	pip install --upgrade netaddr shade functools32
	pip install --upgrade pyvmomi vconnector
	pip install --upgrade ansible
}

debian(){
	apt update
	apt install libsasl2-dev libldap2-dev libssl-dev \
		python-dev build-essential python-virtualenv \
		python-pip libssl-dev sshpass -y
	pip install --upgrade pip
}

ubuntu18(){
	add-apt-repository universe -y
	add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe" -y
	apt update
	apt install libsasl2-dev libldap2-dev libssl-dev \
		python-dev build-essential python3-venv \
		libffi-dev python3-pip libssl-dev sshpass -y
	pip3 install --upgrade pip
	pip3 install --upgrade pyvmomi
}

centos(){
	yum install epel-release -y
	yum install \
		python-virtualenv python-pip \
		python-devel gcc gcc-c++ make \
		cmake python-simplejson openssl-devel \
		libffi libffi-devel pyOpenSSL pycryptopp \
		libselinux-python python2 python-simplejson \
		python-devel openldap-devel -y
	pip install --upgrade pip
	install_pip
}

case `get_so -s` in
        elementary|Debian) debian ;;
	Ubuntu)
		case `get_so -v` in
			18.04) ubuntu18 ;;
			*) debian ;;
		esac
		;;
        CentOS) centos ;;
        Red) if_rhel ;;
esac
