#!/bin/bash

pip install --upgrade pip
pip install --upgrade setuptools
pip install --upgrade paramiko requests
pip install --upgrade PyYAML Jinja2 httplib2
pip install --upgrade six markupsafe ecdsa
pip install --upgrade shade apache-libcloud
pip install --upgrade boto PyOpenSSL python-ldap
pip install --upgrade sklearn joblib pyparsing
pip install --upgrade wrapt debtcollector pytz
pip install --upgrade debtcollector monotonic
pip install --upgrade pyvmomi vconnector
pip install --upgrade netaddr shade functools32
pip install --upgrade python-openstackclient
pip install --upgrade python-neutronclient
pip install --upgrade ansible
