#!/bin/bash
# para streaming de video no servidor usando vlc modo texto
# cvlc v4l2:///dev/video0 :v4l2-standard= \
#     :input-slave=alsa://hw:0,0 \
#     :live-caching=300 \
#     :sout="#transcode{vcodec=WMV2,vb=800,scale=1,acodec=wma2,ab=128,channels=2,samplerate=44100}:http{dst=:8080/stream.wmv}"
# nesse caso ira estar em bind na porta 8080
# para acessar o streaming no client
# vlc http://192.168.111.252:8080/stream.wmv
#
# para foto segue mais um exemplo
# fswebcam --set lights=on --set brightness=50% --set framerate=5 -r 640x480 --jpeg 85 -D 1 web-cam-shot.jpg

brilho="$1"

remoto="bash /home/nariga/aqua-photo $brilho"
inhost="fswebcam --set brightness=$brilho% -r 640x480 --jpeg 100 -D 1 /home/nariga/AquaPicture/web-cam-shot.jpg"

test "$2" = "remoto" && comando=$remoto
test "$2" = "local" && comando=$inhost

ssh lenovo "$comando"
scp lenovo:AquaPicture/web-cam-shot.jpg /home/nariga/web-cam-shot.jpg
ssh lenovo 'rm /home/nariga/AquaPicture/web-cam-shot.jpg'

eog /home/nariga/web-cam-shot.jpg
rm /home/nariga/web-cam-shot.jpg
