#!/bin/bash
# converte arquivos mp3 ou flac para mp3 128 kbps
# arquivos convertidos ficam dentro de mp3
mkdir mp3
for f in *
do
    extencao=$(echo ${f##*.} | tr A-Z a-z)

    [ "$extencao" = "flac" ] && {
        echo "convertendo $f de flac para mp3"
        flac -cd "$f" | lame -b 128 - "${f%.*}".mp3 || erro="true"
    }

    [ "$extencao" = "mp3" ] && {
        echo "convertendo $f de mp3 para mp3"
        lame -b 128 "$f" mp3/"${f%.*}".mp3 || erro="true"
    }

    # nao executa se gerar erro na conversao do arquivo
    # esse bloco ainda nao foi testato
    #[ "$erro" = "true" ] || {
    #    echo "substituindo $file"
    #    rm -f $file
    #    mv mp3/"${f%.*}".mp3 .
    #}
done
