#!/bin/bash

basic(){
	yum -y install http://resources.ovirt.org/pub/yum-repo/ovirt-release36.rpm
	yum -y install nfs-utils ntp
	timedatectl set-timezone America/Sao_Paulo
	default_services="ntpd rpcbind"
	systemctl enable $default_services
	systemctl start $default_services
}

engine(){
	echo "Deploy de ovirt engine"
	basic
	mkdir -p /var/lib/exports/data
	mkdir -p /var/lib/exports/iso

cat > /etc/exports.d/ovirt-engine.exports << EOF
/var/lib/exports/data   192.168.111.0/24(rw,no_root_squash)
EOF

	yum -y install ovirt-engine screen
	systemctl start nfs-server
	systemctl enable nfs-server

	# engine-setup # rodar em modo silencioso
}

hosted(){
	echo "Deploy de ovirt host"
	basic
	yum install -y ovirt-hosted-engine-setup

	# hosted-engine --deploy # rodar em modo silencioso
}

host_vm(){
	# fake_kvm_support = true >> /etc/vdsm/vdsm.conf   [vars]
	echo "options kvm-intel nested=1" > /etc/modprobe.d/kvm-intel.conf
	# echo "GRUB_CMDLINE_LINUX kvm-intel.nested=1" >> /etc/systemctl/grub
	grub2-mkconfig -o /boot/grub2/grub.cfg
	yum install vdsm-hook-faqemu vdsm-hook-nestedvt -y
	systemctl restart vdsmd.service
}

msg_padrao="
\nflag padrao, valores aceitaveis:
\n -e --engine  -> deploy de server engine
\n -h --hosted  -> deploy do client hosted
\n -v --version -> exibe versao deste script
\n -h --help    -> exibe essa mensagem
"
while test -n "$1"
do
	case $1 in
		-e | --engine) engine ;;
		-h | --hosted) hosted ;;
		-v | --version) echo "0.1" ;;
		*) echo -e $msg_padrao
	esac
	shift
done
