#!/bin/bash
mount -a
CONFIG="/etc/offline-repo.conf"

packages_install(){
	rpm -qa | grep yum-utils || yum install -y yum-utils
	rpm -qa | grep createrepo || yum install -y createrepo
}

create_repo(){
	while read LINHA
	do
		[ "$(echo $LINHA | cut -c1)" = '#' ] && continue
		[ "$LINHA" ] || continue
		set - $LINHA
		chave=$(echo $1 | tr A-Z a-z)
		shift
		valor=$*

		case "$chave" in
			basedir) BASEDIR=$valor ;;
			*) repositorios=$(echo "$chave $repositorios $valor")
		esac
	done < "$CONFIG"
	[ ! -d $BASEDIR ] && mkdir -p $BASEDIR

	for repos in `echo $repositorios`
	do
		echo -e "\n---------> Criando repositorio $repos"
		cd $BASEDIR
		reposync -n -l -r $repos
		repomanage -o -c $repos | xargs rm -fv

		if [ ! -f $BASEDIR/$repos/repodata/repomd.xml ]
		then
			echo "----> $BASEDIR/$repos/repodata/repomd.xml sendo CRIADO"
			rm -rf $BASEDIR/$repos/repodata
			rm -rf $BASEDIR/$repos/.repodata
			echo "----> Criando grupos de pacotes para $repos"
			createrepo $repos -g comps.xml &> /dev/null || {
				echo "----> Criacao de grupos de pacotes FALHOU... criando sem grupo"
				createrepo $repos
			}
		else
			echo "----> $BASEDIR/$repos/repodata/repomd.xml sendo ATUALIZADO"
			echo "----> Atualizando grupos de pacotes para $repos"
			createrepo --update $repos -g comps.xml &> /dev/null || {
				echo "----> Atualizacao de grupos de pacotes FALHOU... atualizando sem grupos"
				createrepo --update $repos
			}
		fi
	done
}
create_repo
echo "-----> Atualizando repomd.xml de $BASEDIR"
createrepo --update $BASEDIR
rm -rf /var/tmp/createrepo* -v
